[versions]
gradle = "8.9.3"
junitVersion = "4.13.2"
kotlinGradlePlugin = "2.1.20"
benchmarkBaselineProfileGradlePlugin = "1.3.4"
benchmarkMacroJunit4 = "1.3.4"
composeBom = "2025.05.01"
espressoCore = "3.6.1"
junit = "1.2.1"
ktlintGradle = "12.2.0"
robolectric = "4.14.1"
uiautomator = "2.3.0"
lifecycleViewModel = "2.9.0"
constraintLayout = "2.2.1"
androidCoreKtx = "1.16.0"
skydovesBalloonVersion = "1.6.12"

[libraries]
androidx-benchmark-macro-junit4 = { module = "androidx.benchmark:benchmark-macro-junit4", version.ref = "benchmarkMacroJunit4" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junit" }
androidx-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "uiautomator" }
benchmark-baseline-profile-gradle-plugin = { module = "androidx.benchmark:benchmark-baseline-profile-gradle-plugin", version.ref = "benchmarkBaselineProfileGradlePlugin" }
constraintLayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintLayout" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
junit = { module = "junit:junit", version.ref = "junitVersion" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinGradlePlugin" }
lifecycleExtensions = { module = "androidx.lifecycle:lifecycle-extensions", version = "2.2.0" }
recyclerView = { module = "androidx.recyclerview:recyclerview", version = "1.4.0" }
lifecycleViewModel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewModel" }
androidKtx = { module = "androidx.core:core-ktx", version.ref = "androidCoreKtx" }
androidAppCompat = { module = "androidx.appcompat:appcompat", version = "1.7.0" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
skydoves-balloon = { module = "com.github.skydoves:balloon", version.ref = "skydovesBalloonVersion" }
skydoves-balloon-compose = { module = "com.github.skydoves:balloon-compose", version.ref = "skydovesBalloonVersion" }
skydovesLandscapist = { module = "com.github.skydoves:landscapist-glide", version = "2.4.9" }
androidMaterial = { module = "com.google.android.material:material", version = "1.12.0" }
canarinho = { module = "com.github.concretesolutions:canarinho", version = "2.0.2" }
glide = { module = "com.github.bumptech.glide:glide", version = "4.16.0" }
circleIndicator = { module = "me.relex:circleindicator", version = "2.1.6" }
expansionPanel = { module = "com.github.florent37:expansionpanel", version = "1.2.4" }
toggleButtonLayout = { module = "com.github.savvyapps:ToggleButtonLayout", version = "1.3.0" }
calendarView = { module = "com.github.prolificinteractive:material-calendarview", version = "2.0.1" }
mpChart = { module = "com.github.PhilJay:MPAndroidChart", version = "v3.1.0" }
skeletonBones = { module = "com.github.EudyContreras:Skeleton-Bones", version = "v1.4.5" }
baselineProfileInstaller = { module = "androidx.profileinstaller:profileinstaller", version = "1.4.1" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
compose-lifecycleViewModel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewModel" }
compose-activity = { module = "androidx.activity:activity-compose", version = "1.10.1" }
compose-androidMaterial3 = { group = "androidx.compose.material3", name =  "material3" }
compose-uiToolingPreview = { group = "androidx.compose.ui", name =  "ui-tooling-preview" }
compose-uiViewBinding = { group = "androidx.compose.ui", name =  "ui-viewbinding" }
compose-uiTooling = { group = "androidx.compose.ui", name =  "ui-tooling" }
compose-uiTestJunit4 = { group = "androidx.compose.ui", name =  "ui-test-junit4" }
compose-uiTestManifest = { group = "androidx.compose.ui", name =  "ui-test-manifest" }
compose-runtimeLiveData = { group = "androidx.compose.runtime", name =  "runtime-livedata" }

[plugins]
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlinGradlePlugin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintGradle" }
