[versions]
gradle = "8.13.1"
junitVersion = "4.13.2"
kotlinGradlePlugin = "2.2.21"
benchmarkBaselineProfileGradlePlugin = "1.4.1"
benchmarkMacroJunit4 = "1.4.1"
composeBom = "2025.11.01"
espressoCore = "3.7.0"
junit = "1.3.0"
ktlintGradle = "12.2.0"
robolectric = "4.16"
uiautomator = "2.3.0"
lifecycleViewModel = "2.10.0"
constraintLayout = "2.2.1"
androidCoreKtx = "1.17.0"
skydovesBalloonVersion = "1.7.3"
lifecycleExtensionsVersion = "2.2.0"
recyclerViewVersion = "1.4.0"
androidAppCompatVersion = "1.7.1"
skydovesLandscapistVersion = "2.6.1"
androidMaterialVersion = "1.13.0"
glideVersion = "5.0.5"
circleIndicatorVersion = "2.1.6"
expansionPanelVersion = "1.2.4"
toggleButtonLayoutVersion = "1.3.0"
calendarViewVersion = "2.0.1"
mpChartVersion = "v3.1.0"
skeletonBonesVersion = "v1.4.5"
baselineProfileInstallerVersion = "1.4.1"
composeActivityVersion = "1.12.0"

[libraries]
androidx-benchmark-macro-junit4 = { module = "androidx.benchmark:benchmark-macro-junit4", version.ref = "benchmarkMacroJunit4" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junit" }
androidx-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "uiautomator" }
benchmark-baseline-profile-gradle-plugin = { module = "androidx.benchmark:benchmark-baseline-profile-gradle-plugin", version.ref = "benchmarkBaselineProfileGradlePlugin" }
constraintLayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintLayout" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
junit = { module = "junit:junit", version.ref = "junitVersion" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinGradlePlugin" }
lifecycleExtensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycleExtensionsVersion" }
recyclerView = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerViewVersion" }
lifecycleViewModel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewModel" }
androidKtx = { module = "androidx.core:core-ktx", version.ref = "androidCoreKtx" }
androidAppCompat = { module = "androidx.appcompat:appcompat", version.ref = "androidAppCompatVersion" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
skydoves-balloon = { module = "com.github.skydoves:balloon", version.ref = "skydovesBalloonVersion" }
skydoves-balloon-compose = { module = "com.github.skydoves:balloon-compose", version.ref = "skydovesBalloonVersion" }
skydovesLandscapist = { module = "com.github.skydoves:landscapist-glide", version.ref = "skydovesLandscapistVersion" }
androidMaterial = { module = "com.google.android.material:material", version.ref = "androidMaterialVersion" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glideVersion" }
circleIndicator = { module = "me.relex:circleindicator", version.ref = "circleIndicatorVersion" }
expansionPanel = { module = "com.github.florent37:expansionpanel", version.ref = "expansionPanelVersion" }
toggleButtonLayout = { module = "com.github.savvyapps:ToggleButtonLayout", version.ref = "toggleButtonLayoutVersion" }
calendarView = { module = "com.github.prolificinteractive:material-calendarview", version.ref = "calendarViewVersion" }
mpChart = { module = "com.github.PhilJay:MPAndroidChart", version.ref = "mpChartVersion" }
skeletonBones = { module = "com.github.EudyContreras:Skeleton-Bones", version.ref = "skeletonBonesVersion" }
baselineProfileInstaller = { module = "androidx.profileinstaller:profileinstaller", version.ref = "baselineProfileInstallerVersion" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
compose-lifecycleViewModel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewModel" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "composeActivityVersion" }
compose-androidMaterial3 = { group = "androidx.compose.material3", name =  "material3" }
compose-uiToolingPreview = { group = "androidx.compose.ui", name =  "ui-tooling-preview" }
compose-uiViewBinding = { group = "androidx.compose.ui", name =  "ui-viewbinding" }
compose-uiTooling = { group = "androidx.compose.ui", name =  "ui-tooling" }
compose-uiTestJunit4 = { group = "androidx.compose.ui", name =  "ui-test-junit4" }
compose-uiTestManifest = { group = "androidx.compose.ui", name =  "ui-test-manifest" }
compose-runtimeLiveData = { group = "androidx.compose.runtime", name =  "runtime-livedata" }

[plugins]
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlinGradlePlugin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintGradle" }
