name: CD

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          # Check out as an admin to allow for pushing back to master
          token: ${{ secrets.GH_TOKEN }}
          # We need to fetch all tags and branches
          fetch-depth: 0

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'
          cache: 'gradle'

      - name: Set git identity
        run: |
          git config --global user.name "Blu Release Bot"
          git config --global user.email "devs@useblu.com.br"

      - name: Command Update Branch
        run: git pull

      - name: Update Tokens
        run: cd scripts && ./update_tokens.sh

      - name: Set latest Ocean version
        run: |
          LATEST_VERSION_TOKENS_LIB_NPM=`npm show @useblu/ocean-tokens version`
          echo "OCEAN_VERSION=$LATEST_VERSION_TOKENS_LIB_NPM-$GITHUB_RUN_NUMBER" >> $GITHUB_ENV

      - name: Increment version
        run: sed -i-e "/VERSION_NAME=/ s/=.*/=$OCEAN_VERSION/g" "ocean-components/version.properties"

      - name: Deleting version temp file
        run: rm -f "ocean-components/version.properties-e"

      - name: Update Ktlint Baseline
        run: ./gradlew ktlintGenerateBaseline

      - name: Commit changes
        run: |
          git add . && git commit -am "chore: update Ocean tokens and release v$OCEAN_VERSION [skip ci]" && git push
          git tag -a "v$OCEAN_VERSION" -m "Release version v$OCEAN_VERSION" && git push --tags

      - name: Publish new version lib
        run: ./gradlew ocean-components:publish
        env:
          GPR_USER: ocean-ops
          GPR_API_KEY: ${{ secrets.GPR_API_KEY }}

      - name: Create Release Notes
        uses: ncipollo/release-action@v1.14.0
        with:
          generateReleaseNotes: true
          tag: v${{ env.OCEAN_VERSION }}
